added vite server to package.json to solve installation issue
BioAnalyticResource/ePlant pull request #14
Opened 2022-09-29 19:55 UTC by jamiewaese

I had to install vite separately in order to run this. I'm not sure why it wasn't in the package.json file. Anyway, now it is!

2022-09-30 23:11 UTC, asherpasha commented
Thanks. Please let me know when it is ready to merge.

2022-10-01 15:01 UTC, jamiewaese commented
It’s just adding a line to the package.json. Should be safe. 

> On Sep 30, 2022, at 7:11 PM, Asher ***@***.***> wrote:
> 
> ﻿
> Thanks. Please let me know when it is ready to merge.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2022-10-01 15:44 UTC, alexwaeseperlman requested changes
It looks like you also committed some design changes to this branch. Do you want to open another pull request?

2022-10-01 16:24 UTC, jamiewaese commented
Not yet, I need to fix something I broke first.

Asher, better not do anything yet. I'll let you know when it's ready.

On Sat, Oct 1, 2022 at 11:44 AM Alex ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> It looks like you also committed some design changes to this branch. Do
> you want to open another pull request?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BioAnalyticResource/ePlant/pull/14#pullrequestreview-1127541076>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABBPNBCW372Z4JBBDKW5YBLWBBL5HANCNFSM6AAAAAAQZDNJV4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-11 15:53 UTC, alexwaeseperlman commented on Eplant/UI/Layout/ViewContainer/LoadingPage.tsx
> +        Loading {props.gene.id + ' data for ' + props.view.name}
This needs to handle the case where `props.gene` is null.

2023-09-12 16:23 UTC, merged