fix: Fixed loading screen colour to match theme
BioAnalyticResource/ePlant pull request #83
Opened 2024-02-01 01:57 UTC by Yukthiw

2024-02-08 16:29 UTC, zkdan approved these changes

2024-02-08 16:31 UTC, zkdan requested changes
On second thought -  given that elsewhere we've used `color` (and CSS uses `color`), I think it'll be more consistent to get rid of the u.

2024-02-08 21:12 UTC, mwkyuen commented
I'm upset to spell colour without the `u`. But consistency is more important, so I begrudgingly agree

2024-02-13 17:37 UTC, zkdan approved these changes
😂 wrong spelling

2024-02-15 21:14 UTC, merged