Routing
BioAnalyticResource/ePlant pull request #97
Opened 2024-02-10 16:49 UTC by alexwaeseperlman

Sorry I took so long. This PR removes all the flex layout logic and stores enough state to create shareable links the url. Currently the urls are pretty long since they include all the data about loaded genes. For example:
```
http://localhost:5173/?gene=%22AT1G01010%22&view=%22publication-viewer%22&genes=%5B%7B%22id%22%3A%22AT1G01010%22%2C%22species%22%3A%22Arabidopsis%22%2C%22annotation%22%3A%22NAC+domain+containing+protein+1%22%2C%22aliases%22%3A%5B%22ANAC001%22%2C%22NAC001%22%2C%22NTL10%22%5D%7D%5D
```

I don't think this is an issue, since we can include a url shortener for cases where people want to share things. Another option would be to include a list of gene ids instead of the data itself, and download the rest of the data on page load.

2024-02-15 22:33 UTC, zkdan requested changes, later dismissed
At the meeting today we talked to Nick who said he would prefer a shorter URL and using the URL params to load the information (as opposed to having it all in the URL and shortening it).

I don't want to block the work you did taking the panes out, so my suggestion is to roll this PR back a couple commits to only include the removal of the panes so we can merge it in. Then routing can be a separate PR by you or someone else if you don't have the time/inclination.

2024-02-15 22:33 UTC, zkdan commented on Eplant/UI/LeftNav/index.tsx
>    React.useEffect(() => {
Can you take out the `React.`s wherever you find them, please? If you get an error, the eslint config file should have a rule (I think `'react/react-in-jsx-scope': 'off',`) that'll fix it.

2024-02-15 22:33 UTC, zkdan commented on Eplant/UI/Layout/ViewContainer/index.tsx
>    const [viewingCitations, setViewingCitations] = React.useState(false)
remove `React.`

2024-02-15 22:33 UTC, zkdan commented on Eplant/config.ts
>  export const useConfig = () => React.useContext(Config)
remove `React.`

2024-06-01 16:50 UTC, Yukthiw commented on Eplant/Eplant.tsx
> +      <Box
Is there a reason we aren't breaking this out into a separate component?

2024-06-01 16:50 UTC, Yukthiw commented on Eplant/UI/Layout/ViewContainer/index.tsx
> +  setView?: (view: View) => void
Nit: Why is this optional?

2024-06-05 23:01 UTC, Yukthiw approved these changes
LGTM

2024-06-06 14:36 UTC, merged